services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://github.com/AFellowSpeedrunner/SmolXP/releases/download/V2.0/SmolXP.2.0.x64.iso"
      REGION: "en-US"
      KEYBOARD: "en-US"
      DISK_SIZE: "2G"
      MANUAL: "Y"
      RAM_SIZE: "512M"
      CPU_CORES: "2"
    devices:
      - /dev/kvm
      - /storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 99999999m
    privileged: true
    

  
