services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://github.com/IL01DI/Tiny10/releases/download/v1/Tiny10.iso"
      REGION: "en-US"
      KEYBOARD: "en-US"
      DISK_SIZE: "32G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

  
